<?php

namespace AppBundle\Repository;

/**
 * DesignerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignerRepository extends \Doctrine\ORM\EntityRepository
{
}
